name: Compile and release

# trigger the workflow manually
on: workflow_dispatch

jobs:
  draft_release:
    name: Create draft release
    runs-on: ubuntu-latest
    steps:
      - name: Get version from tag
        id: tag_name
        run: echo "RELEASE_VERSION=$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Create draft release
        run: gh release create --draft "$tag" --title "$tag" --notes "${{ steps.changelog_reader.outputs.changes }}"
      - name: Upload universalJavaApplicationStub.sh asset
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run:
          cp ./src/universalJavaApplicationStub ./universalJavaApplicationStub.sh
          gh release upload ${{ env.RELEASE_VERSION }} ./universalJavaApplicationStub.sh

  compile:
    name: Compile the stub
    needs: draft_release # we need to know the upload URL
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install shc via HomeBrew
        run: |
          brew install shc
          shc -h

      - name: Compile universalJavaApplicationStub
        run: |
          echo "Running shc..."
          shc -r -f src/universalJavaApplicationStub

      - name: Build universalJavaApplicationStub x86_64
        run: |
          echo "Running clang for universalJavaApplicationStub.x86_64"
          clang -o universalJavaApplicationStub.x86_64 -target x86_64-apple-macos10.10 src/universalJavaApplicationStub.x.c 
          strip universalJavaApplicationStub.x86_64

      - name: Build universalJavaApplicationStub arm64
        run: |
          echo "Running clang for universalJavaApplicationStub.arm64"
          clang -o universalJavaApplicationStub.arm64 -target arm64-apple-macos11 src/universalJavaApplicationStub.x.c
          strip universalJavaApplicationStub.arm64

      - name: Build universal universalJavaApplicationStub
        run: |
          echo "Runnning lipo"
          lipo -create -output universalJavaApplicationStub universalJavaApplicationStub.x86_64 universalJavaApplicationStub.arm64
          strip universalJavaApplicationStub
          chmod ug=rwx,o=rx universalJavaApplicationStub

      - name: Build nativeJavaApplicationStub
        run: |
          make universal

      - name: Upload compiled assets
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run:
          cp build/x86_64/nativeJavaApplicationStub ./nativeJavaApplicationStub.x86_64
          cp build/arm64/nativeJavaApplicationStub ./nativeJavaApplicationStub.arm64
          cp build/universal/nativeJavaApplicationStub ./nativeJavaApplicationStub
          gh release upload ${{ needs.draft_release.outputs.tag }} \
            ./universalJavaApplicationStub.x86_64 \
            ./universalJavaApplicationStub.arm64 \
            ./universalJavaApplicationStub \
            ./nativeJavaApplicationStub.x86_64 \
            ./nativeJavaApplicationStub.arm64 \
            ./nativeJavaApplicationStub

  publish_release:
    name: Publish drafted release
    needs: [ draft_release, compile ]
    runs-on: ubuntu-latest
    steps:
      - name: Publish Release
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: gh release edit ${{ needs.draft_release.outputs.tag }}